# -*- coding: utf-8 -*-
"""AI Kelompok 12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T8hySJ38Rs4T9NJwAeh4RwlMCPI6T3yu
"""

import pandas as pd

df = pd.read_csv("data.csv", sep=',', on_bad_lines='skip')

print("DATA:")
print(df.head())

print("\nCOLUMNS:")
print(df.columns)

X = df['password']
y = df['strength']

from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(analyzer='char')
X = X.fillna('') # Replace NaN values with empty strings
X = vectorizer.fit_transform(X)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)
print("Accuracy:", accuracy)

password = ["abc123"]

X_new = vectorizer.transform(password)
pred = model.predict(X_new)

print(pred)

if pred[0] == 0:
    print("Password Lemah")
elif pred[0] == 1:
    print("Password Sedang")
elif pred[0] == 2:
    print("Password Kuat")

password = input("Masukkan password: ")

X_new = vectorizer.transform([password])
pred = model.predict(X_new)

if pred[0] == 0:
    print("Password Lemah")
elif pred[0] == 1:
    print("Password Sedang")
elif pred[0] == 2:
    print("Password Kuat")

import pickle

pickle.dump(model, open("model.pkl", "wb"))
pickle.dump(vectorizer, open("vectorizer.pkl", "wb"))